services:
  localstack:
    image: localstack/localstack
    ports:
      - "4566:4566"
    environment:
      - SERVICES=s3,ec2
      - AWS_ACCESS_KEY_ID=test
      - AWS_SECRET_ACCESS_KEY=test
    volumes:
      - "${LOCALSTACK_VOLUME_DIR:-./volume}:/var/lib/localstack"
      
  flask-app:
    build:
      context: .
      dockerfile: Dockerfile.prod
    ports:
      - "5000:5000"  # Your app's port
    environment:
      - FLASK_ENV=development
      - LOCALSTACK_ENDPOINT=http://localstack:4566